/**
 * generated by Xtext 2.35.0
 */
package org.pnpl.model.variability.editor.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.pnpl.model.variability.editor.PNPL_variabilityRuntimeModule;
import org.pnpl.model.variability.editor.PNPL_variabilityStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class PNPL_variabilityIdeSetup extends PNPL_variabilityStandaloneSetup {
  @Override
  public Injector createInjector() {
    PNPL_variabilityRuntimeModule _pNPL_variabilityRuntimeModule = new PNPL_variabilityRuntimeModule();
    PNPL_variabilityIdeModule _pNPL_variabilityIdeModule = new PNPL_variabilityIdeModule();
    return Guice.createInjector(Modules2.mixin(_pNPL_variabilityRuntimeModule, _pNPL_variabilityIdeModule));
  }
}
