/**
 * generated by Xtext 2.35.0
 */
package org.pnpl.model.variability.editor.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class PNPL_variabilityUiModule extends AbstractPNPL_variabilityUiModule {
  public PNPL_variabilityUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
