/**
 * generated by Xtext 2.35.0
 */
package org.pnpl.model.variability.editor.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
@SuppressWarnings("all")
public class PNPL_variabilityDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
