/**
 * generated by Xtext 2.35.0
 */
package org.pnpl.model.variability.editor.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
@SuppressWarnings("all")
public class PNPL_variabilityLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public PNPL_variabilityLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
}
